language: ruby
rvm:
    - 1.9
    - 2.0
    - 2.1
    - 2.2
    - 2.3
    - ruby-2.4.0-preview2
    - ruby-head
sudo: required
before_install:
    - gem update --system
    - gem install bundler -v '~>1.13'
    - bundler --version
install:
    - make
    - gem build mpcat.gemspec
    - gem install mpcat-*.gem
    - gem list -l mpcat
script:
    - make test
    - cd
    - which -a mpcat
    - mpcat --version
